/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq;

import com.zlargon.springdemo.jooq.tables.Book;
import com.zlargon.springdemo.jooq.tables.records.BookRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * spring_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(
    Book.BOOK,
    DSL.name("book_pkey"),
    new TableField[] { Book.BOOK.ID },
    true
  );
}
