/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq;

import com.zlargon.springdemo.jooq.tables.Book;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringDemo extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>spring_demo</code>
   */
  public static final SpringDemo SPRING_DEMO = new SpringDemo();

  /**
   * The table <code>spring_demo.book</code>.
   */
  public final Book BOOK = Book.BOOK;

  /**
   * No further instances allowed
   */
  private SpringDemo() {
    super("spring_demo", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(Book.BOOK);
  }
}
