/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq;

import com.zlargon.springdemo.jooq.tables.Book;

/**
 * Convenience access to all tables in spring_demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>spring_demo.book</code>.
   */
  public static final Book BOOK = Book.BOOK;
}
